# Generated by Django 2.0.2 on 2018-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('songid', models.CharField(max_length=255)),
                ('lastPlayed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('songid', models.CharField(max_length=255)),
                ('heartrate', models.IntegerField()),
                ('rating', models.FloatField()),
                ('time', models.IntegerField(default=1197)),
                ('songsSinceLastPlayed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlayCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('playCounter', models.IntegerField(default=0)),
            ],
        ),
    ]
