# Generated by Django 2.0.2 on 2018-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('songid', models.IntegerField()),
                ('heartrate', models.IntegerField()),
                ('time', models.DateTimeField(verbose_name='auto_now_add=True')),
            ],
        ),
    ]
